services:
  scrap-conventions:
    image: ghcr.io/alizee-m/scrap-conventions:latest
    container_name: scrap-conventions
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - scrap-conventions-cache:/app/cache

volumes:
  scrap-conventions-cache:
