services:
  scrap-conventions:
    image: ghcr.io/alizee-m/scrap-conventions:latest
    container_name: scrap-conventions
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - /share/scrap-conventions/cache:/app/cache
